#!/bin/bash  # ← Изменили здесь

message="$(cat $1)"
requiredPattern="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|bump)(\([\w\-]+\))?!?: .+$"
if ! [[ $message =~ $requiredPattern ]]; then
  echo "------------------------------------------"
  echo "🚨 Wrong commit message! 😕"
  echo " "
  echo "The commit message must have this format:"
  echo "<type>: <what was done>"
  echo " "
  echo "Allowed type: feat, fix, chore, docs, style, refactor, perf, test, build, ci, revert, bump"
  echo " "
  echo "Example: add login button"
  echo " "
  echo "Your commit message was:"
  echo "$message"  # ← Также добавили кавычки здесь для безопасности
  echo " "
  echo "Help: https://www.conventionalcommits.org/en/v1.0.0/"
  echo "------------------------------------------"
  exit 1
fi