name: Frontend CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run typecheck

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm test

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: |
          set +e
          OUTPUT=$(npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --no-interactive)
          STATUS=$?

          # Достаём ссылки на билд
          STORYBOOK_URL=$(echo "$OUTPUT" | grep -oE 'https://[^\ ]*chromatic\.com/[^\ ]*' | grep -v 'manage')
          BUILD_URL=$(echo "$OUTPUT" | grep -oE 'https://www\.chromatic\.com/build\?appId=[^\ ]*')

          echo ""
          echo "🔗 **Storybook:** $STORYBOOK_URL"
          echo "🔍 **Build details:** $BUILD_URL"
          echo ""
          if [ $STATUS -ne 0 ]; then
            echo "🚨 **Ошибки скриншотных тестов!** Пожалуйста, просмотрите информацию по ссылке и подтвердите изменения."
            echo "📌 Ссылка на изменения: $BUILD_URL"
            exit 1
          else
            echo "✅ No visual changes detected."
          fi
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint, typecheck, unit-tests, chromatic]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
