name: Frontend CI/CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run typecheck

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm test

  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Run Chromatic
        id: chromatic
        run: |
          set +e
          OUTPUT=$(npm run chromatic 2>&1)
          EXIT_CODE=$?

          echo "$OUTPUT" > chromatic.log

          # Ищем ссылку на билд Chromatic
          BUILD_URL=$(echo "$OUTPUT" | grep -Eo 'https://www.chromatic.com/build\?appId[^ ]+')

          echo "build_url=$BUILD_URL" >> $GITHUB_OUTPUT

          exit $EXIT_CODE
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Chromatic failed message
        if: failure()
        run: |
          echo "::error::❌ Chromatic визуальные тесты не прошли!"
          if [ -n "${{ steps.chromatic.outputs.build_url }}" ]; then
            echo "📄 Отчёт Chromatic: ${{ steps.chromatic.outputs.build_url }}"
          else
            echo "⚠️ Ссылка на билд не найдена в выводе."
          fi
          echo ""
          echo "Что делать:"
          echo "1. Откройте отчёт и посмотрите визуальные изменения."
          echo "2. Если они ожидаемы — обновите снапшоты."
          echo "3. Если нет — исправьте код и запустите снова."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, lint, typecheck, unit-tests, chromatic]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
